version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      cron: "14 3 * * */7"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      cron: "14 3 * * */7"
    open-pull-requests-limit: 10

